CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y

# ZMK Studio
# ZMK Studioが有効になっている場合、Centralがスリープ状態から復帰しない問題が発生するため、ZMK Studioは無効にした
# https://github.com/zmkfirmware/zmk/issues/3195
#CONFIG_ZMK_STUDIO=y
#CONFIG_ZMK_STUDIO_LOCKING=n

# Dongle Screen YADS config
CONFIG_DONGLE_SCREEN_SYSTEM_ICON=2
CONFIG_DONGLE_SCREEN_DEFAULT_BRIGHTNESS=5
CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=y
CONFIG_DONGLE_SCREEN_BRIGHTNESS_STEP=3
CONFIG_DONGLE_SCREEN_WPM_ACTIVE=n
CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=0

# ZMK Stack sizes
CONFIG_ZMK_BLE_THREAD_STACK_SIZE=2048
CONFIG_ZMK_LOW_PRIORITY_THREAD_STACK_SIZE=2048
CONFIG_INPUT_THREAD_STACK_SIZE=2048
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_STACK_SIZE=2048
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=3096